services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=restaraunt-reviews'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=deve'
    ports:
      - '127.0.0.1:5432:5432'
