spring:
  application:
    name: restaurant-reviews
  jpa:
    hibernate:
      dd1-auto: validate
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100
        serialization-mode: via-dto