spring:
  application:
    name: restaurant-reviews
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      dd1-auto: validate
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100
        serialization-mode: via-dto

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1h
    issuer: restaurant-reviews